### PR TITLE
Fix ffmpeg dependency and don't import project in setup.py

### LINKED ISSUE #1: Wrong dependency `python-ffmpeg`. Should be: `ffmpeg-python`
Otherwise, an attempt to run `gpmf.io.extract_gpmf_stream("GX010028.MP4")` will result in the following error:

```
~/.pyvenv/py38/lib/python3.9/site-packages/gpmf/io.py in find_gpmf_stream(fname)
     23         RuntimeError: If no stream found.
     24         """
---> 25         probe = ffmpeg.probe(fname)
     26 
     27         for s in probe["streams"]:

AttributeError: module 'ffmpeg' has no attribute 'probe'
```

Nice project by the way. I like it a lot!

### PR DESCRIPTION
**Pull request by ashtuchkin**
Fixes #1.

Also it's a bad practice to import the project in setup.py, as at the time of setup the environment likely doesn't have the required dependencies like numpy. There are a couple ways to resolve this while keeping the 2 versions in the same place, see https://packaging.python.org/en/latest/guides/single-sourcing-package-version/.

### CODE REVIEW

File: setup.py [hunk 1]
```diff
@@ -1,6 +1,6 @@
 from setuptools import setup, find_packages
 import pathlib
-from gpmf import __version__
+__version__ = "0.1"
```
Comment (kalvdans) [inline setup.py:3]: Great! Remove the `__version__` definition in `gpmf/__init__.py` too so we don't have duplicate definitions that risk being out of sync.

**Review by kalvdans — APPROVED** [review]

**Comment by ashtuchkin** [comment]
@kalvdans do you have write access to the original repository?

**Comment by kalvdans** [comment]
> @kalvdans do you have write access to the original repository?

No, sorry. I can't merge, just helping out reviewing.
